name: bfast
description: BFast client sdk for flutter
version: 3.0.0-beta.3
homepage: http://github.com/fahamutech/bfast-flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.1
  sembast: ^2.4.5
  path_provider: ^1.6.11
  socket_io_client: ^0.9.10
  sembast_sqflite: ^1.0.0
  sqflite: ^1.3.1
  flutter:
    sdk: flutter

dev_dependencies:
#  test: ^1.15.1
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

# flutter: