name: bfast
description: BFast client sdk for flutter
version: 5.0.0
homepage: http://github.com/fahamutech/bfast-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.1
  http: ^0.13.5
  socket_io_client: ^2.0.0
  path_provider: ^2.0.11
#  tekartik_app_flutter_sembast:
#    git:
#      url: https://github.com/tekartik/app_flutter_utils.dart
#      ref: dart2_3
#      path: app_sembast
#    version: '>=0.1.0'

dev_dependencies:
  #  test: ^1.15.1
  flutter_test:
    sdk: flutter

# flutter: