name: bfast
description: BFast client sdk for flutter
version: 4.1.1
homepage: http://github.com/fahamutech/bfast-flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.2
  path: ^1.8.0
  sembast: ^3.0.0+4
  path_provider: ^2.0.1
  socket_io_client: ^0.9.12
  sembast_sqflite: ^2.0.0+1
  sembast_web: ^2.0.0+2
  sqflite: ^2.0.0+3
  flutter:
    sdk: flutter

dev_dependencies:
  #  test: ^1.15.1
  mockito: ^5.0.3
  flutter_test:
    sdk: flutter

# flutter: