name: bfast
description: BFast client sdk for flutter
version: 4.0.0-beta.1
homepage: http://github.com/fahamutech/bfast-flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.2
  path: 1.8.0-nullsafety.1
  sembast: ^2.4.8
  path_provider: ^1.6.24
  socket_io_client: ^0.9.11
  # sembast_sqflite: ^1.0.0
  sembast_web: ^1.2.0
  sqflite: ^1.3.2+1
  flutter:
    sdk: flutter

dev_dependencies:
#  test: ^1.15.1
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

# flutter: